### ISSUE TITLE
Bug - ArgoCD Sync Fails Sometimes

### ISSUE THREAD

**Issue by dwinchell** [ploigos/ploigos-gitlab-library#3]
The deploy step fails sometimes and we don't understand why.

Here is an example: https://github.com/ploigos/spring-petclinic/runs/6617694376?check_suite_focus=true

```
        2022-05-26T22:56:32+00:00                       Namespace  ploigos-petclinic-petclinic-main-dev  ploigos-petclinic-petclinic-main-dev                           Running   Synced              namespace/ploigos-petclinic-petclinic-main-dev unchanged
```
...
```
        Message
            Error deploying to environment (DEV): Error synchronization ArgoCD Application (ploigos-petclinic-petclinic-main-dev): 

              RAN: /usr/bin/argocd app sync --prune --timeout 130 --retry-limit 3 ploigos-petclinic-petclinic-main-dev
```

Success Criteria:
* We understand the root cause and have documented it on this ticket
* We can run the pipeline successfully without the deploy step failing under whatever conditions we find out trigger the bug

 Notes:
* The conditions under which this happens might be "on the next pipeline run after a failed run"
* It might be that app actually syncs successfully, but the pipeline still fails
* This might be a timeout issue.

**Comment by aarongreen85** [comment]
@dwinchell Gerard and I both don't have power to assign ourselves to this issue. @gfulton-redhat

**Comment by dwinchell** [comment]
How about now?

**Comment by dwinchell** [comment]
This was a bug in argocd-cli. Fixed it by adding the --async option to the argocd wait command.
